type Project {
  name: String
  tagline: String
  contributors: [User]
}

{
  project(name: "GraphQL") {
    tagline
  }
}

query getCity($city: String) {
  city(name: $city) {
    name
    country
    weather {
      temperature
      precipitation
    }
  }
}

fragment User on User {
  name
  email
}
